language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=Example
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2.4

  matrix:
    - DB=mysql CAKE_VERSION=2.4
    - DB=mysql CAKE_VERSION=2.5
    - DB=mysql CAKE_VERSION=2.6

matrix:
  include:
      php: 5.4
      env:
        - CODECOVERAGE=1
      php: 5.4
      env:
        - PHPCS=1
      php: 5.4
      env:
        - FOC_VALIDATE=1 FOC_TRAVIS=1

before_script:
  - cp -R example_plugin ../example_plugin && cd ../example_plugin
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
